### PR TITLE
Updated mySome, myEvery, myReduce

### PR DESCRIPTION
**Pull request by BrajanHalili**
Added mySome, myEvery and myReduce to the javascript file.
<javascript_functions.js> Added mySome, myEvery and myReduce as functions. All three work in O(n) time.
             mySome - checks every element until it finds one that returns true as an input to a given function.
             myEvery - checks every element until it finds one that does not return true as an input to a given function.
             myReduce - goes through every element and executes the given function on each iteration, returning the cumulative value + initial value (optional).

### CODE REVIEW

**Comment by rezkhan7** [comment]
All functions look great!

**Comment by Utrejo1125** [comment]
looks good!

**Comment by LilyKizir** [comment]
reviewed

**Review by LilyKizir — APPROVED** [review]

**Review by Utrejo1125 — APPROVED** [review]

**Comment by rezkhan7** [comment]
reviewed

**Review by LilyKizir — APPROVED** [review]

**Review by rezkhan7 — APPROVED** [review]

**Pull request merged**
