### PR TITLE
Did myEach, myMap, myFiter

### PR DESCRIPTION
**Pull request by rezkhan7**
myEach - traverses through array and applies a callback function
myMap - applies a callback functions to every element and returns a new array with applied changes
myFilter- filters out elements based on callback function and returns a new array

### CODE REVIEW

**Comment by BrajanHalili** [comment]
All of the functions work as intended.

**Comment by Utrejo1125** [comment]
functions look great

**Comment by LilyKizir** [comment]
reviewed

**Review by Utrejo1125 — COMMENTED** [review]
nice

**Review by BrajanHalili — APPROVED** [review]

**Review by LilyKizir — APPROVED** [review]
looks good

**Review by Utrejo1125 — APPROVED** [review]

**Pull request merged**
